# Spring Configure
spring:
  batch:
    jdbc:
      initialize-schema: NEVER
  
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@s3.moara.org:6030/orcl
    username: wigoVoc
    password: wigoVoc
jasypt:
  encryptor:
    bean: jasyptStringEncryptor       
# Log
logging:
  config: classpath:logback-dev.xml
